Don't require license.key when DEPLOY_USER & DEPLOY_PASSWORD specified

diff --git a/scripts/init b/scripts/init
--- a/scripts/init
+++ b/scripts/init
@@ -99,9 +99,11 @@ if [ "x${SLAB_ALLOC_ARENA}" = 'x' ]; then
 fi
 
 
-if [ ! -f "/etc/wallarm/license.key" ]; then
-  echo "ERROR: no license key in /etc/wallarm/license.key" >&2
-  exit 1
+if [ -z "$DEPLOY_USER" -o -z "$DEPLOY_PASSWORD" ]; then
+  if [ ! -f "/etc/wallarm/license.key" ]; then
+    echo "ERROR: no DEPLOY_USER or DEPLOY_PASSWORD and no license key in /etc/wallarm/license.key" >&2
+    exit 1
+  fi
 fi
 
 
