Do not pass secrets to register-node as arguments, it is unsecure

diff --git a/scripts/init b/scripts/init
--- a/scripts/init
+++ b/scripts/init
@@ -64,13 +64,11 @@ register_node() {
     echo "Node registartion skipped - node.yaml already exists"
   elif [ -n "$NODE_UUID" ] \
     && [ -n "$NODE_SECRET" ] \
-    && [ -n "$DEPLOY_TOKEN" ]
+    && [ -n "$WALLARM_API_TOKEN" ]
   then
     /usr/share/wallarm-common/register-node \
       $args \
-        --uuid "$NODE_UUID" \
-        --secret "$NODE_SECRET" \
-        --token "$DEPLOY_TOKEN"
+        --uuid "$NODE_UUID"
   elif [ -n "$NODE_UUID" ] \
     && [ -n "$NODE_SECRET" ]
   then
@@ -87,7 +85,7 @@ register_node() {
       --password "$DEPLOY_PASSWORD"
   else
     /usr/share/wallarm-common/register-node \
-      $args --token "$DEPLOY_TOKEN"
+      $args
   fi
 }
 
@@ -206,9 +204,9 @@ if [ -n "$POSTANALYTIC_ADDRESS" ] && [ -n "$POSTANALYTIC_ONLY" ]; then
   exit 1
 fi
 
-if ([ -z "$DEPLOY_USER" ] || [ -z "$DEPLOY_PASSWORD" ]) && [ -z "$DEPLOY_TOKEN" ]; then
+if ([ -z "$DEPLOY_USER" ] || [ -z "$DEPLOY_PASSWORD" ]) && [ -z "$WALLARM_API_TOKEN" ]; then
   if [ ! -f "/etc/wallarm/private.key" ]; then
-    echo "ERROR: no DEPLOY_USER, DEPLOY_PASSWORD or DEPLOY_TOKEN and no private key in /etc/wallarm/private.key" >&2
+    echo "ERROR: no DEPLOY_USER, DEPLOY_PASSWORD or WALLARM_API_TOKEN and no private key in /etc/wallarm/private.key" >&2
     exit 1
   fi
 fi
